import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ParticlesComponent } from "@/components/particle";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <ParticlesComponent />
      <body className={`relative ${inter.className}`}>
        <Toaster position="bottom-right" />
        {children}
      </body>
    </html>
  );
}
